default: &default
  adapter: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

sqlite: &sqlite
  <<: *default
  adapter: sqlite3

development:
  <<: *sqlite
  database: db/development.sqlite3

test:
  <<: *sqlite
  database: db/test.sqlite3

production:
  <<: *default
  database: pressie
